### ISSUE TITLE
BE 추가 구현해야하는 기능

### ISSUE THREAD

**Issue by yejoo0310** [Notice4MusicalTicketing/BE#25]
# Title
추가해야 하는 기능 정리

# Description
기능에 대한 부가 설명

# Task
- [x] 게시물 검색 기능
- [x] 게시물 댓글 기능
- [x] 게시물 필터 기능
- [x] 뮤지컬 정보와 게시물 연결
